[package]
name = "this-week-in-open-source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.15"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
