env:
  COMMENT_BODY: ${{ github.event.comment.body }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  schedule:
    # Every Sunday 23:00
    - cron: '0 23 * * 0'
  label:
    types: [labeled, unlabeled]

jobs:
  create_twios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Configure local git
        run: |
          git config --global user.email "twios@twios_test_dev.com"
          git config --global user.name "TWIOS Dev"
      - name: Generate Comment
        run: |
          GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN cargo run -- comment --users=BobrImperator --config-path=sample_config.json > comment.txt
      - name: Generate TWIOS
        run: GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN cargo run -- --users=BobrImperator --config-path=sample_config.json
      - name: Create TWIOS on schedule
        if: github.event.schedule || github.event.pull_request
        run: |
          FORMATTED_DATE="$(date +"%Y-%m-%d")"
          BRANCH_NAME="twios-$FORMATTED_DATE"
          mkdir -p twios/
          git fetch
          git add . && git commit -m "$BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME
          gh pr create --base main --head $BRANCH_NAME --title "TWIOS $FORMATTED_DATE" --body-file comment.txt
    
  edit_twios:
    runs-on: ubuntu-latest
    if: github.event.pull_request.body
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Configure local git
        run: |
          git config --global user.email "twios@twios_test_dev.com"
          git config --global user.name "TWIOS Dev"
      - name: Read PR commetn body
        run: | 
          GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN cargo run -- comment --users=BobrImperator --config-path=sample_config.json --comment=${{ github.event.pull_request.body }}
      - name: Generate Comment
        run: |
          GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN cargo run -- comment --users=BobrImperator --config-path=sample_config.json > comment.txt
      - name: Generate TWIOS
        run: GITHUB_PERSONAL_TOKEN=$GITHUB_TOKEN cargo run -- --users=BobrImperator --config-path=sample_config.json
      - name: Create TWIOS on schedule
        if: github.event.schedule || github.event.pull_request
        run: |
          FORMATTED_DATE="$(date +"%Y-%m-%d")"
          BRANCH_NAME="twios-$FORMATTED_DATE"
          mkdir -p twios/
          git fetch
          git add . && git commit -m "$BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME
          gh pr create --base main --head $BRANCH_NAME --title "TWIOS $FORMATTED_DATE" --body-file comment.txt
